### ISSUE TITLE
404

### ISSUE THREAD

**Issue by maehr** [CollectionBuilder/collectionbuilder-sheets#29]
https://github.com/CollectionBuilder/collectionbuilder-sheets/blob/7fbb2c4102ad4a94b9d2c2cc0d9fb2da22259b4b/pages/metadata.md?plain=1#L20

<img width="725" alt="Screenshot 2024-09-16 at 10 36 19" src="https://github.com/user-attachments/assets/46777cb1-b7ed-418e-baa5-bc34aaad7712">

**Comment by evanwill** [comment]
thank you! I swapped it out for popping up the setup modal, 33aa398fea147c2a173a16343adff1eba8ec072a
